spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/ais_task?useUnicode=true&characterEncoding=UTF-8"
    username: "root"
    password: "123456"
  #    type: com.mchange.v2.c3p0.ComboPooledDataSource

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql